#!/usr/bin/env python3
"""Generate the canonical feature glossary from code.

Single source of truth for feature *names* is the code:

  1. src/approach-retreat.js — ResultFeatureTracker: the structured
     comment block ("The nine features mirror the canonical extractor...")
     and the getFeatures() return keys.
  2. attentional-foraging/scripts/m4_nb21_hybrid_rerun.py — M4_FEATURES,
     the parity-verified (1e-6) Python extractor.
  3. analysis/attcur-validation/run_analysis.py — the WILD (ACD) analog
     feature dict returned by compute_features().

The prose metadata (units, definitions, model membership) is curated in
GLOSSARY below, but the script FAILS (exit 1) whenever the curated name
set drifts from what the code computes — add/rename a feature in code
and this script refuses to emit until the glossary row exists. That is
the drift guard requested after the CIKM 2026 reviews (Reviewer 2:
names used but never defined; Reviewer 3: §3.4 doesn't teach the seven).

Outputs:
  approach-retreat/docs/feature-glossary.md          (markdown table)
  cikm-leakycursor/feature_glossary.tex              (booktabs table)
  approach-retreat/README.md                         (between markers,
                                                      only if present)

Run:  python3 scripts/gen_feature_glossary.py
No dependencies beyond the standard library.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent  # approach-retreat/
JS_SRC = REPO / "src" / "approach-retreat.js"
PY_EXTRACTOR = Path(
    "/Users/andyed/Documents/dev/attentional-foraging/scripts/m4_nb21_hybrid_rerun.py"
)
WILD_SRC = REPO / "analysis" / "attcur-validation" / "run_analysis.py"

OUT_MD = REPO / "docs" / "feature-glossary.md"
OUT_TEX = Path("/Users/andyed/Documents/dev/cikm-leakycursor/feature_glossary.tex")
README = REPO / "README.md"

MARKER_START = "<!-- feature-glossary:start — generated by scripts/gen_feature_glossary.py — do not hand-edit -->"
MARKER_END = "<!-- feature-glossary:end -->"

# ─────────────────────────────────────────────────────────────────────
# Curated glossary metadata. Keys MUST exactly match the names parsed
# from code (guarded below). Fields:
#   units       — measurement units / value type
#   defn        — plain-language definition
#   formula     — formula sketch over d(t) = cursor-to-AOI distance (markdown)
#   formula_tex — the same sketch as LaTeX math (used verbatim in the .tex)
#   models      — which model set (M1–M4 / analogs) consumes it
# ─────────────────────────────────────────────────────────────────────

M34 = "M3, M4"

GLOSSARY = {
    # ── The nine LAB approach features (JS tracker ↔ Python extractor) ──
    "min_dist": dict(
        units="px",
        defn="Minimum cursor-to-AOI-center distance over the whole trial (closest approach).",
        formula="min_t d(t)",
        formula_tex='$\\min_t d(t)$',
        models=M34,
    ),
    "mean_dist": dict(
        units="px",
        defn="Mean cursor-to-AOI-center distance over all samples.",
        formula="(1/n) Sum_t d(t)",
        formula_tex='$(1/n)\\sum_t d(t)$',
        models=M34,
    ),
    "final_dist": dict(
        units="px",
        defn="Distance at the last cursor sample. Structurally pinned by gaze-cursor convergence at click time.",
        formula="d(t_end)",
        formula_tex='$d(t_{\\mathrm{end}})$',
        models="excluded from M4 (leakage screen, §5.2)",
    ),
    "retreat_dist": dict(
        units="px",
        defn="Post-closest-approach drift: final distance minus minimum distance. Zero by construction when click lock-on holds.",
        formula="final_dist − min_dist",
        formula_tex='$d(t_{\\mathrm{end}}) - \\min_t d(t)$',
        models="excluded from M4 (leakage screen, §5.2)",
    ),
    "dwell_in_proximity_ms": dict(
        units="ms",
        defn="Cumulative time the cursor spends within the 100 px proximity zone of the AOI center; inter-sample gaps ≥ 2000 ms (tab-switch / away-from-keyboard) are not accumulated.",
        formula="Sum Δt where d(t) < 100 px, Δt < 2 s",
        formula_tex='$\\sum \\Delta t$ where $d(t) < 100$\\,px, $\\Delta t < 2$\\,s',
        models=M34,
    ),
    "mean_approach_velocity": dict(
        units="px/s",
        defn="Mean directed approach rate; positive = closing on the AOI (negative on average by design: retreat intervals dominate a trial).",
        formula="mean_t v(t), v(t) = −Δd/Δt",
        formula_tex='$\\overline{v(t)}$, $v(t) = -\\Delta d / \\Delta t$',
        models=M34,
    ),
    "max_approach_velocity": dict(
        units="px/s",
        defn="Peak single-interval directed approach rate.",
        formula="max_t v(t)",
        formula_tex='$\\max_t v(t)$',
        models=M34,
    ),
    "direction_changes": dict(
        units="count",
        defn="Sign flips in the directed-velocity sequence (approach ↔ retreat), counting transitions through zero.",
        formula="#{sign(v_t) ≠ sign(v_{t−1})}",
        formula_tex='$\\#\\{\\mathrm{sign}(v_t) \\neq \\mathrm{sign}(v_{t-1})\\}$',
        models=M34,
    ),
    "frac_decreasing": dict(
        units="0–1",
        defn="Fraction of sample transitions on which distance decreased (cursor moving toward the AOI).",
        formula="#{Δd < 0} / (n−1)",
        formula_tex='$\\#\\{\\Delta d < 0\\} / (n{-}1)$',
        models=M34,
    ),
    "sample_count": dict(
        units="count",
        defn="Number of cursor samples aggregated for this AOI. Diagnostic field emitted by the JS tracker; not a model input.",
        formula="n",
        formula_tex='$n$',
        models="— (diagnostic)",
    ),
    # ── Dwell aggregate baseline (LAB) ──
    "total_dwell_ms": dict(
        units="ms",
        defn=(
            "Per-result total dwell, the M2/M3 baseline. LAB referent: sum of "
            "gaze-fixation durations attributed to the result's AOI "
            "(attentional-foraging/scripts/compute_cursor_approach_features.py). "
            "The JS library separately emits a cursor analog under the same name "
            "— getSignals().total_dwell_ms, the sum of per-episode in-AOI "
            "cursor dwell — same name, different sensor; do not conflate."
        ),
        formula="LAB: Sum fixation durations on AOI; JS: Sum episode dwell_ms",
        formula_tex='LAB: $\\sum$ fixation durations on AOI; JS: $\\sum$ episode \\texttt{dwell\\_ms}',
        models="M2, M3 (and §5.3's eight-feature M3-no-position vector); excluded from M4",
    ),
    # ── WILD (ACD) analog features ──
    "dwell_in_target_ms": dict(
        units="ms",
        defn="WILD analog of the dwell baseline: cumulative cursor time inside the target-ad bounding box (Δt counted when both interval endpoints are in-target).",
        formula="Sum Δt where in_target(t) ∧ in_target(t+1)",
        formula_tex='$\\sum \\Delta t$ where in-target at both interval endpoints',
        models="WILD M2/M3-analogs; excluded from M4-analog (§5.1)",
    ),
    "n_target_entries": dict(
        units="count",
        defn="Cursor entries into the target bounding box (out→in transitions; +1 if the session starts in-target).",
        formula="#{in_target: 0→1}",
        formula_tex='$\\#\\{\\mathrm{out} \\to \\mathrm{in}\\ \\mathrm{transitions}\\}$',
        models="WILD M3/M4-analogs (§5.1)",
    ),
    "n_events": dict(
        units="count",
        defn="Total telemetry events in the session; stands in (with session_ms) for the velocity terms ACD's low-rate log cannot support.",
        formula="count(events)",
        formula_tex='$|\\mathrm{events}|$',
        models="WILD M3/M4-analogs (§5.1)",
    ),
    "session_ms": dict(
        units="ms",
        defn="Session duration: last minus first event timestamp.",
        formula="t_last − t_first",
        formula_tex='$t_{\\mathrm{last}} - t_{\\mathrm{first}}$',
        models="WILD M3/M4-analogs (§5.1)",
    ),
}

GROUPS = [
    (
        "Per-AOI approach features (LAB, AdSERP)",
        [
            "min_dist",
            "mean_dist",
            "final_dist",
            "retreat_dist",
            "dwell_in_proximity_ms",
            "mean_approach_velocity",
            "max_approach_velocity",
            "direction_changes",
            "frac_decreasing",
            "sample_count",
        ],
    ),
    ("Dwell aggregate baseline (LAB, AdSERP)", ["total_dwell_ms"]),
    (
        "WILD analog features (ACD, attcur-validation)",
        ["dwell_in_target_ms", "n_target_entries", "n_events", "session_ms"],
    ),
]


def fail(msg: str) -> None:
    print(f"DRIFT GUARD FAILED: {msg}", file=sys.stderr)
    sys.exit(1)


# ─────────────────────────────────────────────────────────────────────
# Parsers
# ─────────────────────────────────────────────────────────────────────

def parse_js(js_text: str):
    """Return (comment_names, getfeatures_keys, has_total_dwell)."""
    # 1. The structured comment block above ResultFeatureTracker:
    #    " *   1. min_dist              — min |Δy| ..."
    comment_names = re.findall(
        r"^\s*\*\s*\d+\.\s+(\w+)\s+—", js_text, re.M
    )
    if not comment_names:
        fail("could not parse the numbered feature comment block in approach-retreat.js")

    # 2. getFeatures() return keys.
    m = re.search(r"getFeatures\(\)\s*\{(.*?)\n  \}", js_text, re.S)
    if not m:
        fail("could not locate getFeatures() body in approach-retreat.js")
    body = m.group(1)
    keys = re.findall(r"^\s+(\w+):", body, re.M)
    if not keys:
        fail("getFeatures() body parsed but no return keys found")

    has_total_dwell = "total_dwell_ms" in js_text
    return comment_names, keys, has_total_dwell


def parse_py_m4(py_text: str):
    m = re.search(r"M4_FEATURES\s*=\s*\[(.*?)\]", py_text, re.S)
    if not m:
        fail("could not locate M4_FEATURES in m4_nb21_hybrid_rerun.py")
    return re.findall(r'"(\w+)"', m.group(1))


def parse_wild(py_text: str):
    m = re.search(r"def compute_features.*?return \{(.*?)\n    \}", py_text, re.S)
    if not m:
        fail("could not locate compute_features() return dict in run_analysis.py")
    return re.findall(r'"(\w+)":', m.group(1))


# ─────────────────────────────────────────────────────────────────────
# Drift guards
# ─────────────────────────────────────────────────────────────────────

def run_guards():
    js_text = JS_SRC.read_text()
    comment_names, gf_keys, has_total_dwell = parse_js(js_text)
    py_m4 = parse_py_m4(PY_EXTRACTOR.read_text())
    wild_keys = parse_wild(WILD_SRC.read_text())

    # Guard 1: comment block == getFeatures keys minus sample_count, same order.
    gf_features = [k for k in gf_keys if k != "sample_count"]
    if comment_names != gf_features:
        fail(
            "JS comment block and getFeatures() disagree:\n"
            f"  comment:      {comment_names}\n"
            f"  getFeatures:  {gf_features}"
        )

    # Guard 2: Python M4_FEATURES == the nine JS features, same order.
    if py_m4 != comment_names:
        fail(
            "Python M4_FEATURES and JS tracker disagree:\n"
            f"  M4_FEATURES:  {py_m4}\n"
            f"  JS:           {comment_names}"
        )

    # Guard 3: total_dwell_ms still exists in the JS (getSignals aggregate).
    if not has_total_dwell:
        fail("total_dwell_ms no longer present in approach-retreat.js")

    # Guard 4: every WILD name in the glossary exists in run_analysis.py.
    wild_glossary = GROUPS[2][1]
    missing = [n for n in wild_glossary if n not in wild_keys]
    if missing:
        fail(f"WILD glossary names missing from run_analysis.py: {missing}")

    # Guard 5: curated glossary keys exactly cover the code-derived set.
    code_names = set(gf_keys) | {"total_dwell_ms"} | set(wild_glossary)
    glossary_names = set(GLOSSARY)
    group_names = [n for _, names in GROUPS for n in names]
    if sorted(group_names) != sorted(glossary_names):
        fail(
            "GROUPS and GLOSSARY disagree: "
            f"{set(group_names) ^ glossary_names}"
        )
    only_code = code_names - glossary_names
    only_glossary = glossary_names - code_names
    if only_code:
        fail(
            f"feature(s) computed in code but missing a glossary row: {sorted(only_code)}"
        )
    if only_glossary:
        fail(
            f"glossary row(s) with no code referent: {sorted(only_glossary)}"
        )

    return comment_names


# ─────────────────────────────────────────────────────────────────────
# Emitters
# ─────────────────────────────────────────────────────────────────────

PROVENANCE = (
    "Generated by `scripts/gen_feature_glossary.py` from "
    "`src/approach-retreat.js` (ResultFeatureTracker), "
    "`attentional-foraging/scripts/m4_nb21_hybrid_rerun.py` (M4_FEATURES, "
    "JS↔Python parity-verified at 1e-6), and "
    "`analysis/attcur-validation/run_analysis.py` (WILD analogs). "
    "Do not hand-edit; rerun the script."
)

INTRO_MD = (
    "All LAB features are transformations of the cursor-to-AOI distance "
    "d(t) = |cursor page-Y − AOI center page-Y| (vertical distance; in a "
    "single-column SERP the horizontal component adds noise without signal), "
    "aggregated over the whole click-buffered trial against each result's "
    "bounding-box center. Directed velocity v(t) = −Δd/Δt is "
    "positive when approaching. Model sets: M1 = rank position only; "
    "M2 = position + total_dwell_ms; M3 = M2 + the seven approach features; "
    "M4 = the seven buffer-robust approach features alone (the nine computed "
    "features minus `final_dist` and `retreat_dist`, which the §5.2 "
    "click-buffer leakage screen excludes). WILD (ACD) analogs re-derive the "
    "vector for cursor+click-only telemetry: eight features after the WILD "
    "leakage screen drops `retreat_dist` (`final_dist` has no WILD referent "
    "— it requires fixation-timed sampling)."
)


def emit_markdown_table() -> str:
    lines = [
        "| Feature | Type / units | Definition | Formula sketch | Model sets |",
        "|---|---|---|---|---|",
    ]
    for group, names in GROUPS:
        lines.append(f"| **{group}** | | | | |")
        for n in names:
            g = GLOSSARY[n]
            lines.append(
                f"| `{n}` | {g['units']} | {g['defn']} | {g['formula']} | {g['models']} |"
            )
    return "\n".join(lines)


def emit_markdown_doc() -> str:
    return (
        f"{MARKER_START}\n\n"
        "# Feature glossary\n\n"
        f"> {PROVENANCE}\n\n"
        f"{INTRO_MD}\n\n"
        f"{emit_markdown_table()}\n\n"
        f"{MARKER_END}\n"
    )


TEX_SPECIALS = {
    "_": r"\_",
    "#": r"\#",
    "%": r"\%",
    "&": r"\&",
    "−": "$-$",
    "≥": "$\\geq$",
    "≠": "$\\neq$",
    "↔": "$\\leftrightarrow$",
    "→": "$\\to$",
    "∧": "$\\wedge$",
    "Δ": "$\\Delta$",
    "—": "---",
    "§": "\\S",
    "–": "--",
}


def tex_escape(s: str) -> str:
    out = []
    for ch in s:
        out.append(TEX_SPECIALS.get(ch, ch))
    return "".join(out)


def emit_tex() -> str:
    header = r"""% ---------------------------------------------------------------------------
% feature_glossary.tex — GENERATED FILE, DO NOT HAND-EDIT.
% Source of truth: approach-retreat/scripts/gen_feature_glossary.py, which
% parses ResultFeatureTracker in approach-retreat/src/approach-retreat.js,
% cross-checks M4_FEATURES in attentional-foraging/scripts/
% m4_nb21_hybrid_rerun.py (JS<->Python parity 1e-6), and the WILD analog
% extractor in approach-retreat/analysis/attcur-validation/run_analysis.py.
% Regenerate:  python3 ~/Documents/dev/approach-retreat/scripts/gen_feature_glossary.py
%
% WHERE TO \input THIS: at the end of §3.4 ("Leaky Cursor Approach
% Features", label the-seven-approach-features-m4-cursor-probe) in
% 3_method_new.tex, immediately after the fig:leakycursor figure block —
% i.e. add the line
%     \input{feature_glossary}
% there. Addresses Reviewer 2 (feature names used but never defined,
% e.g. total_dwell_ms vs dwell_in_target_ms) and Reviewer 3 (§3.4 does
% not teach the seven features). Uses only booktabs + adjustbox, both
% already loaded by 0_paper.tex. Reference it as Table~\ref{tab:glossary}.
% ---------------------------------------------------------------------------
"""
    rows = []
    for group, names in GROUPS:
        rows.append(r"\midrule")
        rows.append(
            r"\multicolumn{4}{@{}l}{\textit{" + tex_escape(group) + r"}} \\"
        )
        rows.append(r"\midrule")
        for n in names:
            g = GLOSSARY[n]
            defn = tex_escape(g["defn"])
            cell = f"{defn} \\emph{{Formula:}} {g['formula_tex']}."
            rows.append(
                f"\\texttt{{{tex_escape(n)}}} & {tex_escape(g['units'])} & "
                f"{cell} & {tex_escape(g['models'])} \\\\"
            )
            rows.append(r"\addlinespace[2pt]")
    body = "\n".join(rows)
    return (
        header
        + r"""
\begin{table*}[t]
\footnotesize
\centering
\caption{\textbf{Feature glossary.} Every behavioral feature named in
this paper, generated from the reference implementations
(\texttt{approach-retreat} JS library and the parity-verified Python
extractor; WILD analogs from the ACD validation harness). All LAB
features are transformations of the cursor-to-AOI distance
$d(t) = |y_{\mathrm{cursor}}(t) - y_{\mathrm{AOI}}|$ (page-space
vertical distance), aggregated over the whole click-buffered trial;
directed velocity $v(t) = -\Delta d / \Delta t$ is positive when
approaching. M4 is the seven buffer-robust features: the nine computed
minus \texttt{final\_dist} and \texttt{retreat\_dist} (\S5.2 leakage
screen). The WILD (ACD) analog vector re-derives the construction for
cursor+click-only telemetry.}
\label{tab:glossary}
\adjustbox{max width=\textwidth}{%
\begin{tabular}{@{}llp{9.2cm}p{4.2cm}@{}}
\toprule
Feature & Units & Definition & Model sets \\
"""
        + body
        + "\n"
        + r"""\bottomrule
\end{tabular}%
}
\end{table*}
"""
    )


def update_readme(table_block: str) -> bool:
    text = README.read_text()
    if MARKER_START not in text or MARKER_END not in text:
        return False
    pattern = re.compile(
        re.escape(MARKER_START) + r".*?" + re.escape(MARKER_END), re.S
    )
    new = pattern.sub(table_block.rstrip("\n"), text)
    README.write_text(new)
    return True


def main():
    run_guards()

    OUT_MD.parent.mkdir(parents=True, exist_ok=True)
    OUT_MD.write_text(emit_markdown_doc())
    print(f"wrote {OUT_MD}")

    OUT_TEX.write_text(emit_tex())
    print(f"wrote {OUT_TEX}")

    readme_block = (
        f"{MARKER_START}\n\n"
        f"### Feature glossary\n\n"
        f"> {PROVENANCE}\n"
        f"> Full version with intro notes: "
        f"[`docs/feature-glossary.md`](docs/feature-glossary.md).\n\n"
        f"{emit_markdown_table()}\n\n"
        f"{MARKER_END}"
    )
    if update_readme(readme_block):
        print(f"updated {README} (between glossary markers)")
    else:
        print(
            f"README markers not found — skipped README update.\n"
            f"  Add these markers to README.md to enable:\n"
            f"  {MARKER_START}\n  {MARKER_END}"
        )


if __name__ == "__main__":
    main()
